---
title: "figures"
output: 
  html_document: 
    css: ~/git/economic-influenza/css/default.css
    fig_caption: yes
    keep_md: yes
    theme: cosmo
  html_notebook: 
    css: ~/git/economic-influenza/css/default.css
    theme: cosmo
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, warning = FALSE, message = FALSE, tidy = TRUE)
```

```{r}
rm(list = ls(all.names = TRUE))
library(ggplot2); library(tidyr); library(dplyr)
library(knitr); library(rmarkdown)
```

```{r}
data <- read.csv("df/icer-all.csv", as.is = TRUE)
df <- data[(data$scenario!="base"),]

df$cases.averted <- as.numeric(df$cases.averted)
df$cases.averted.per100k <- as.numeric(df$cases.averted.per100k)
df$icer.case.averted <- as.numeric(df$icer.case.averted)
df$deaths.averted <- as.numeric(df$deaths.averted)
df$deaths.averted.per100k <- as.numeric(df$ deaths.averted.per100k)
df$icer.death.averted <- as.numeric(df$icer.death.averted)
df$dalys <- as.numeric(df$dalys)
df$dalys.per100k <- as.numeric(df$dalys.per100k)
df$dalys.averted <- as.numeric(df$dalys.averted)
df$dalys.averted.per100k <- as.numeric(df$dalys.averted.per100k)
df$icer.daly.averted <- as.numeric(df$icer.daly.averted)
```

```{r}
# subset relevant efficacies
df2 <- df[!df$v.eff %in% c(60), ]
table(df2$v.eff, useNA = 'always')

df3 <- df2[!(df2$scenario == 'vax70' & df2$v.eff %in% c(40,50)), ]
table(df3$scenario, df3$v.eff, useNA = 'always')

# factors
df3$age <- factor(df3$age, levels = c("0-4 yrs", "5-19 yrs", "20-64 yrs", "65+ yrs", "All"))
df3$risk <- factor(df3$risk, levels = c("High", "Non-high", "All"))
df3$scenario <- factor(df3$scenario, levels = c("vaxbase", "vax70"))
df3$v.eff <- factor(df3$v.eff)
```

# Table: ICERs.
```{r}
t1 <- df3[c("scenario", "age", "risk", "v.eff", "icer.case.averted", "icer.death.averted", "icer.daly.averted")] %>%
  gather("icer.case.averted", "icer.death.averted", "icer.daly.averted", key = "icer", value = "value") %>%
  spread(risk, value) %>%
  arrange(scenario, v.eff, icer)
head(t1)

#write.csv(t1, "table-icer.csv")
```

# Table: Cases, deaths, DALYs per 100,000 population.
```{r}
t2 <- df3[c("scenario", "age", "risk", "v.eff", "cases.per100k", "deaths.per100k", "dalys.per100k")] %>%
  gather("cases.per100k", "deaths.per100k", "dalys.per100k", key = "metric", value = "value") %>%
  spread(risk, value) %>%
  arrange(scenario, v.eff, metric)
head(t2)

#write.csv(t2, "table-rates.csv")
```

# Table: Cases, deaths, DALYs averted per 100,000
```{r}
t3 <- df3[c("scenario", "age", "risk", "v.eff", "cases.averted.per100k", "deaths.averted.per100k", "dalys.averted.per100k")] %>%
  gather("cases.averted.per100k", "deaths.averted.per100k", "dalys.averted.per100k", key = "metric", value = "value") %>%
  spread(risk, value) %>%
  arrange(scenario, v.eff, metric)
head(t3)

#write.csv(t3, "table-averted-rates.csv")
```


# FIGURES

```{r}
# subset by age group
age_group_df <- df3[(df3$risk=="All"),]

# subset by risk group
risk_group_df <- df3[(df3$risk!="All"),]
```

# Figure: ICERs.
```{r}
# icer per case averted
ggplot(age_group_df, aes(x = age, y = icer.case.averted, color = v.eff, group = v.eff)) + labs(color = "Vaccine \nefficacy") +
  geom_point() + geom_line(linetype = "dotted") + ylab("$ saved per case averted") +
  facet_grid(~ scenario) + ggtitle("ICER per case averted")

# icer per death averted
ggplot(age_group_df, aes(x = age, y = icer.death.averted, color = v.eff, group = v.eff)) + labs(color = "Vaccine \nefficacy") +
  geom_point() + geom_line(linetype = "dotted") + ylab("$ saved per death averted") +
  facet_grid(~ scenario)+ ggtitle("ICER per death averted")

# icer per daly averted
ggplot(age_group_df, aes(x = age, y = icer.daly.averted, color = v.eff, group = v.eff)) + labs(color = "Vaccine \nefficacy") +
  geom_point() + geom_line(linetype = "dotted") + ylab("$ saved per DALY averted") +
  facet_grid(~ scenario) + ggtitle("ICER per DALY averted")


## Alternatively:
# icer per case averted
ggplot(age_group_df, aes(x = age, y = icer.case.averted, color = v.eff, group = v.eff)) + labs(color = "Vaccine \nefficacy") +
  geom_point() + geom_line(linetype = "dotted") + ylab("$ saved per case averted") +
  facet_grid(v.eff ~ scenario) + ggtitle("ICER per case averted")

# icer per death averted
ggplot(age_group_df, aes(x = age, y = icer.death.averted, color = v.eff, group = v.eff)) + labs(color = "Vaccine \nefficacy") +
  geom_point() + geom_line(linetype = "dotted") + ylab("$ saved per death averted") +
  facet_grid(v.eff ~ scenario) + ggtitle("ICER per death averted")

# icer per DALY averted
ggplot(age_group_df, aes(x = age, y = icer.daly.averted, color = v.eff, group = v.eff)) + labs(color = "Vaccine \nefficacy") +
  geom_point() + geom_line(linetype = "dotted") + ylab("$ saved per DALY averted") +
  facet_grid(v.eff ~ scenario) + ggtitle("ICER per DALY averted")
```

# Figures: Cases.
```{r}
# cases
ggplot(age_group_df, aes(x = age, y = cases, color = v.eff, group = v.eff)) + geom_point() + geom_line(linetype = "dotted") +
  ggtitle("Number of cases in each age group by vaccine efficacy") + facet_grid(~scenario)

ggplot(age_group_df, aes(x = age, y = cases, color = v.eff, group = v.eff)) + labs(color = "Vaccine \nefficacy") +
  geom_point() + geom_line(linetype = "dotted") + ylab("cases") +
  facet_grid(v.eff~scenario) + ggtitle("Number of cases in each age group by vaccine efficacy")

ggplot(df3, aes(x = age, y = cases, color = risk, group = risk)) + labs(color = "Risk \ngroup") +
  geom_point() + geom_line(linetype = "dotted") + ylab("cases") +
  facet_grid(v.eff~scenario) + ggtitle("Number of cases in each age and risk group by vaccine efficacy")

ggplot(age_group_df, aes(x = age, y = cases, color = v.eff, group = v.eff)) + labs(color = "Vaccine \nefficacy") +
  geom_point() + geom_line(linetype = "dotted") + ylab("cases") +
  facet_grid(scenario~v.eff) + ggtitle("Number of cases in each age group by vaccine efficacy")

ggplot(df3, aes(x = age, y = cases, color = risk, group = risk)) + labs(color = "Vaccine \nefficacy") +
  geom_point() + geom_line(linetype = "dotted") + ylab("cases") +
  facet_grid(scenario~v.eff) + ggtitle("Number of cases in each age group by vaccine efficacy")
```

# Figures: Deaths per 100k
```{r}
# deaths
ggplot(age_group_df, aes(x = age, y = deaths.per100k, color = v.eff, group = v.eff)) + geom_point() + geom_line(linetype = "dotted") + ggtitle("Deaths per 100k in each age group by vaccine efficacy") + facet_grid(~scenario)

ggplot(age_group_df, aes(x = age, y = deaths.per100k, color = v.eff, group = v.eff)) + labs(color = "Vaccine \nefficacy") +
  geom_point() + geom_line(linetype = "dotted") + ylab("deaths per 100k") +
  facet_grid(v.eff~scenario) + ggtitle("Deaths per 100k in each age group by vaccine efficacy")

ggplot(df3, aes(x = age, y = deaths.per100k, color = risk, group = risk)) + labs(color = "Risk \ngroup") +
  geom_point() + geom_line(linetype = "dotted") + ylab("deaths per 100k") +
  facet_grid(v.eff~scenario) + ggtitle("Deaths per 100k in each age and risk group by vaccine efficacy")

ggplot(age_group_df, aes(x = age, y = deaths.per100k, color = v.eff, group = v.eff)) + labs(color = "Vaccine \nefficacy") +
  geom_point() + geom_line(linetype = "dotted") + ylab("deaths per 100k") +
  facet_grid(scenario~v.eff) + ggtitle("Deaths per 100k in each age group by vaccine efficacy")

ggplot(df3, aes(x = age, y = deaths.per100k, color = risk, group = risk)) + labs(color = "Vaccine \nefficacy") +
  geom_point() + geom_line(linetype = "dotted") + ylab("deaths per 100k") +
  facet_grid(scenario~v.eff) + ggtitle("Deaths per 100k in each age group by vaccine efficacy")
```

# Figures: DALYs per 100k
```{r}
# DALYs per 100k
ggplot(age_group_df, aes(x = age, y = dalys.per100k, color = v.eff, group = v.eff)) + geom_point() + geom_line(linetype = "dotted") + ggtitle("DALYs per 100k in each age group by vaccine efficacy") + facet_grid(~scenario)

ggplot(age_group_df, aes(x = age, y = dalys.per100k, color = v.eff, group = v.eff)) + labs(color = "Vaccine \nefficacy") +
  geom_point() + geom_line(linetype = "dotted") + ylab("DALYs per 100k") +
  facet_grid(v.eff~scenario) + ggtitle("DALYs per 100k in each age group by vaccine efficacy")

ggplot(df3, aes(x = age, y = dalys.per100k, color = risk, group = risk)) + labs(color = "Risk \ngroup") +
  geom_point() + geom_line(linetype = "dotted") + ylab("DALYs per 100k") +
  facet_grid(v.eff~scenario) + ggtitle("DALYs per 100k in each age and risk group by vaccine efficacy")

ggplot(age_group_df, aes(x = age, y = dalys.per100k, color = v.eff, group = v.eff)) + labs(color = "Vaccine \nefficacy") +
  geom_point() + geom_line(linetype = "dotted") + ylab("DALYs per 100k") +
  facet_grid(scenario~v.eff) + ggtitle("DALYs per 100k in each age group by vaccine efficacy")

ggplot(df3, aes(x = age, y = dalys.per100k, color = risk, group = risk)) + labs(color = "Vaccine \nefficacy") +
  geom_point() + geom_line(linetype = "dotted") + ylab("DALYs per 100k") +
  facet_grid(scenario~v.eff) + ggtitle("DALYs per 100k in each age group by vaccine efficacy")
```



```{r eval=FALSE, include=FALSE}
## BASEVAX Figures: Cases
vaxbase_df <- df3[(df3$scenario=="vaxbase"),]
vaxbase_df_risk <- risk_group_df[(risk_group_df$scenario=="vaxbase"),]
vaxbase_df_age <- age_group_df[(age_group_df$scenario=="vaxbase"),]

ggplot(vaxbase_df_age, aes(x = age, y = cases, color = v.eff, group = v.eff)) + geom_point() + geom_line(linetype = "dotted") + ggtitle("Number of cases in each age group by vaccine efficacy")

ggplot(vaxbase_df_age, aes(x = age, y = cases, color = v.eff, group = v.eff)) + labs(color = "Vaccine \nefficacy") +
  geom_point() + geom_line(linetype = "dotted") + ylab("cases") +
  facet_grid(~v.eff) + ggtitle("Number of cases in each age group by vaccine efficacy")

ggplot(vaxbase_df, aes(x = age, y = cases, color = risk, group = risk)) + labs(color = "Risk \ngroup") +
  geom_point() + geom_line(linetype = "dotted") + ylab("cases") +
  facet_grid(~v.eff) + ggtitle("Number of cases in each age and risk group by vaccine efficacy")

ggplot(vaxbase_df, aes(x = age, y = cases, color = risk, group = risk)) + labs(color = "Risk \ngroup") +
  geom_point() + geom_line(linetype = "dotted") + ylab("cases") +
  facet_grid(v.eff~risk) + ggtitle("Number of cases in each age and risk group by vaccine efficacy")


## BASEVAX Figures: Deaths per 100k 
ggplot(vaxbase_df_age, aes(x = age, y = deaths.per100k, color = v.eff, group = v.eff)) + geom_point() + geom_line(linetype = "dotted") + ggtitle("Deaths per 100k in each age group by vaccine efficacy")

ggplot(vaxbase_df_age, aes(x = age, y = deaths.per100k, color = v.eff, group = v.eff)) + labs(color = "Vaccine \nefficacy") +
  geom_point() + geom_line(linetype = "dotted") + ylab("deaths") +
  facet_grid(~v.eff) + ggtitle("Deaths per 100k in each age group by vaccine efficacy")

ggplot(vaxbase_df, aes(x = age, y = deaths.per100k, color = risk, group = risk)) + labs(color = "Risk \ngroup") +
  geom_point() + geom_line(linetype = "dotted") + ylab("deaths") +
  facet_grid(~v.eff) + ggtitle("Deaths per 100k in each age and risk group by vaccine efficacy")

ggplot(vaxbase_df, aes(x = age, y = deaths.per100k, color = risk, group = risk)) + labs(color = "Risk \ngroup") +
  geom_point() + geom_line(linetype = "dotted") + ylab("deaths") +
  facet_grid(v.eff~risk) + ggtitle("Deaths per 100k in each age and risk group by vaccine efficacy")


## BASEVAX Figures: DALYs per 100k
ggplot(vaxbase_df_age, aes(x = age, y = dalys.per100k, color = v.eff, group = v.eff)) + geom_point() + geom_line(linetype = "dotted") +  ggtitle("DALYs per 100k in each age group by vaccine efficacy")

ggplot(vaxbase_df_age, aes(x = age, y = dalys.per100k, color = v.eff, group = v.eff)) + labs(color = "Vaccine \nefficacy") +
  geom_point() + geom_line(linetype = "dotted") + ylab("DALYs") +
  facet_grid(~v.eff) + ggtitle("DALYs per 100k in each age group by vaccine efficacy")

ggplot(vaxbase_df, aes(x = age, y = dalys.per100k, color = risk, group = risk)) + labs(color = "Risk \ngroup") +
  geom_point() + geom_line(linetype = "dotted") + ylab("DALYs") +
  facet_grid(~v.eff) + ggtitle("DALYs per 100k in each age and risk group by vaccine efficacy")

ggplot(vaxbase_df, aes(x = age, y = dalys.per100k, color = risk, group = risk)) + labs(color = "Risk \ngroup") +
  geom_point() + geom_line(linetype = "dotted") + ylab("DALYs") +
  facet_grid(v.eff~risk) + ggtitle("DALYs per 100k in each age and risk group by vaccine efficacy")
```


```{r eval=FALSE, include=FALSE}
## Vax 70% FIGURES: Cases
vax70_df <- df3[(df3$scenario=="vax70"),]
vax70_df_risk <- risk_group_df[(risk_group_df$scenario=="vax70"),]
vax70_df_age <- age_group_df[(age_group_df$scenario=="vax70"),]

ggplot(vax70_df_age, aes(x = age, y = cases, color = v.eff, group = v.eff)) + geom_point() + geom_line(linetype = "dotted") +
  ggtitle("Number of cases in each age group by vaccine efficacy")

ggplot(vax70_df_age, aes(x = age, y = cases, color = v.eff, group = v.eff)) + labs(color = "Vaccine \nefficacy") +
  geom_point() + geom_line(linetype = "dotted") + ylab("cases") +
  facet_grid(~v.eff) + ggtitle("Number of cases in each age group by vaccine efficacy")

ggplot(vax70_df, aes(x = age, y = cases, color = risk, group = risk)) + labs(color = "Risk \ngroup") +
  geom_point() + geom_line(linetype = "dotted") + ylab("cases") +
  facet_grid(~v.eff) + ggtitle("Number of cases in each age and risk group by vaccine efficacy")

ggplot(vax70_df, aes(x = age, y = cases, color = risk, group = risk)) + labs(color = "Risk \ngroup") +
  geom_point() + geom_line(linetype = "dotted") + ylab("cases") +
  facet_grid(v.eff~risk) + ggtitle("Number of cases in each age and risk group by vaccine efficacy")


## Vax 70% FIGURES: Deaths
ggplot(vax70_df_age, aes(x = age, y = deaths.per100k, color = v.eff, group = v.eff)) + geom_point() + geom_line(linetype = "dotted") + ggtitle("Deaths per 100k in each age group by vaccine efficacy")

ggplot(vax70_df_age, aes(x = age, y = deaths.per100k, color = v.eff, group = v.eff)) + labs(color = "Vaccine \nefficacy") +
  geom_point() + geom_line(linetype = "dotted") + ylab("deaths") +
  facet_grid(~v.eff) + ggtitle("Deaths per 100k in each age group by vaccine efficacy")

ggplot(vax70_df, aes(x = age, y = deaths.per100k, color = risk, group = risk)) + labs(color = "Risk \ngroup") +
  geom_point() + geom_line(linetype = "dotted") + ylab("deaths") +
  facet_grid(~v.eff) + ggtitle("Deaths per 100k in each age and risk group by vaccine efficacy")

ggplot(vax70_df, aes(x = age, y = deaths.per100k, color = risk, group = risk)) + labs(color = "Risk \ngroup") +
  geom_point() + geom_line(linetype = "dotted") + ylab("deaths") +
  facet_grid(v.eff~risk) + ggtitle("Deaths per 100k in each age and risk group by vaccine efficacy")


## Vax 70% FIGURES: DALYs
ggplot(vax70_df_age, aes(x = age, y = dalys.per100k, color = v.eff, group = v.eff)) + geom_point() + geom_line(linetype = "dotted") +
  ggtitle("DALYs per 100k in each age group by vaccine efficacy")

ggplot(vax70_df_age, aes(x = age, y = dalys.per100k, color = v.eff, group = v.eff)) + labs(color = "Vaccine \nefficacy") +
  geom_point() + geom_line(linetype = "dotted") + ylab("DALYs") +
  facet_grid(~v.eff) + ggtitle("DALYs per 100k in each age group by vaccine efficacy")

ggplot(vax70_df, aes(x = age, y = dalys.per100k, color = risk, group = risk)) + labs(color = "Risk \ngroup") +
  geom_point() + geom_line(linetype = "dotted") + ylab("DALYs") +
  facet_grid(~v.eff) + ggtitle("DALYs per 100k in each age and risk group by vaccine efficacy")

ggplot(vax70_df, aes(x = age, y = dalys.per100k, color = risk, group = risk)) + labs(color = "Risk \ngroup") +
  geom_point() + geom_line(linetype = "dotted") + ylab("DALYs") +
  facet_grid(v.eff~risk) + ggtitle("DALYs per 100k in each age and risk group by vaccine efficacy")
```

