---
title: "Healthy vax vs. Prevalent vax (10,20%)"
output: 
  html_notebook: 
    code_folding: hide
    fig_caption: yes
    number_sections: yes
    theme: cosmo
    toc: yes
  html_document: 
    fig_caption: yes
    keep_md: yes
    number_sections: yes
    theme: cosmo
    toc: yes
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	warning = TRUE,
	cache = TRUE,
	tidy = TRUE
)
```

```{r}
rm(list = ls(all.names = TRUE))

library(ggplot2)
library(tidyr)
library(dplyr)
library(knitr)
library(rmarkdown)
library(formatR)
```

```{r}
data <- read.csv("df/icer-all.csv", as.is = TRUE)

# subset comparator = prevalent vaccination
df <- data[!(data$reference=="none"),]

df$cost.diff.per100k <- as.numeric(df$cost.diff.per100k)
df$cases.averted <- as.numeric(df$cases.averted)
df$cases.averted.per100k <- as.numeric(df$cases.averted.per100k)
df$icer.case.averted <- as.numeric(df$icer.case.averted)
df$deaths.averted <- as.numeric(df$deaths.averted)
df$deaths.averted.per100k <- as.numeric(df$ deaths.averted.per100k)
df$icer.death.averted <- as.numeric(df$icer.death.averted)
df$dalys <- as.numeric(df$dalys)
df$dalys.per100k <- as.numeric(df$dalys.per100k)
df$dalys.averted <- as.numeric(df$dalys.averted)
df$dalys.averted.per100k <- as.numeric(df$dalys.averted.per100k)
df$icer.daly.averted <- as.numeric(df$icer.daly.averted)
```

```{r}
# factors
df$age <- factor(df$age, levels = c("0-4 yrs", "5-19 yrs", "20-64 yrs", "65+ yrs", "All"))
df$risk <- factor(df$risk, levels = c("High", "Non-high", "All"))
df$scenario <- factor(df$scenario, levels = c("vaxbase", "vax70"))
df$v.eff <- factor(df$v.eff)
```

# Tables

```{r eval=FALSE, include=FALSE}
## Table: ICERs.
t1 <- df[c("scenario", "age", "risk", "v.eff", "icer.case.averted", "icer.death.averted", "icer.daly.averted")] %>%
  gather("icer.case.averted", "icer.death.averted", "icer.daly.averted", key = "icer", value = "value") %>%
  spread(risk, value) %>%
  arrange(scenario, v.eff, icer)
head(t1)
#write.csv(t1, "df/df2-icer.csv")

## Table: Cases, deaths, DALYs per 100,000 population.
t2 <- df[c("scenario", "age", "risk", "v.eff", "cases.per100k", "deaths.per100k", "dalys.per100k")] %>%
  gather("cases.per100k", "deaths.per100k", "dalys.per100k", key = "metric", value = "value") %>%
  spread(risk, value) %>%
  arrange(scenario, v.eff, metric)
head(t2)
#write.csv(t2, "df/df2-rates.csv")

## Table: Cases, deaths, DALYs averted per 100,000
t3 <- df[c("scenario", "age", "risk", "v.eff", "cases.averted.per100k", "deaths.averted.per100k", "dalys.averted.per100k")] %>%
  gather("cases.averted.per100k", "deaths.averted.per100k", "dalys.averted.per100k", key = "metric", value = "value") %>%
  spread(risk, value) %>%
  arrange(scenario, v.eff, metric)
head(t3)
#write.csv(t3, "df/df2-averted-rates.csv")
```

# Subset data.

```{r}
# subset healthy people 20% VE(compared to prevalent)
df_hp <- df[(df$reference=="vaxbase"),]
df_10 <- df_hp[(df_hp$v.eff == '10'),]
df_20 <- df_hp[(df_hp$v.eff == '20'),]

# subset prevalent 40% VE (compared to none)
df_pv <- df[(df$scenario=="vaxbase"),]
df_40 <- df_pv[(df_pv$v.eff == '40'),]
```


## 20% VE: $ per case averted
```{r}
ggplot(df_20, aes(x = age, y = icer.case.averted, group = risk, color = risk)) +
  geom_point() + geom_line(linetype = "dotted") + labs(x = "Age group", color = "Risk group") + 
  ylab("$ saved per case averted") + ggtitle("Healthy People Vaccination (20% VE): ICER per case averted")
```


## 20% VE: $ per death averted
```{r}
ggplot(df_20, aes(x = age, y = icer.death.averted, group = risk, color = risk)) +
  geom_point() + geom_line(linetype = "dotted") + labs(x = "Age group", color = "Risk group") + 
  ylab("$ saved per case averted") + ggtitle("Healthy People Vaccination (20% VE): ICER per death averted")
```

## 20% VE: $ per DALY averted
```{r}
ggplot(df_20, aes(x = age, y = icer.daly.averted, group = risk, color = risk)) +
  geom_point() + geom_line(linetype = "dotted") + labs(x = "Age group", color = "Risk group") + 
  ylab("$ saved per case averted") + ggtitle("Healthy People Vaccination (20% VE): ICER per DALY averted")
```

## 20% VE: Cases, cases averted
```{r}
g4 <- ggplot(df_20, aes(x = age, group = risk, color = risk)) +
  geom_point() + geom_line(linetype = "dotted") + labs(x = "Age group", color = "Risk group", title = "Healthy People Vaccination (20% VE)")

g4 + aes(y = cases) + labs(y = "Cases")
g4 + aes(y = cases.per100k) + labs(y = "Cases per 100k")
g4 + aes(y = cases.averted) + labs(y = "Cases averted")
g4 + aes(y = cases.averted.per100k) + labs(y = "Cases averted per 100k")
```

## 20% VE: Deaths, deaths averted
```{r}
g4 + aes(y = deaths) + labs(y = "Deaths")
g4 + aes(y = deaths.per100k) + labs(y = "Deaths (per 100k)")
g4 + aes(y = deaths.averted) + labs(y = "Deaths averted")
g4 + aes(y = deaths.averted.per100k) + labs(y = "Deaths averted (per 100k)")
```

## 20% VE: DALYs, DALYs averted
```{r}
g4 + aes(y = dalys) + labs(y = "DALYs")
g4 + aes(y = dalys.per100k) + labs(y = "DALYs (per 100k)")
g4 + aes(y = dalys.averted) + labs(y = "DALYs averted")
g4 + aes(y = dalys.averted.per100k) + labs(y = "DALYs averted (per 100k)")
```

## Cost-effectiveness plane: HP vs. PV

```{r}
l <- labs(x = "DALYs averted (per 100k)", y = "Cost (per 100k)", title = "Healthy People Vaccination Scenario")

# All VE%
a <- ggplot(df_hp, aes(x = dalys.averted.per100k, y = cost.diff.per100k)) + l

a + aes(color = risk, group = risk) + labs(color = "Risk") + geom_point() + facet_grid(v.eff ~ age)
a + aes(color = age, group = age) + labs(color = "Age group") + geom_point() + facet_grid(v.eff ~ risk)
```

## EXTRA: Cost-effectiveness plane (10% and 20% VE)

```{r}
# 10% VE
a1 <- ggplot(df_10, aes(x = dalys.averted.per100k, y = cost.diff.per100k)) + l +
  labs(title = "Cost-effectiveness plane: Healthy People vs. Prevalent (10% VE)")
a1 + aes(color = risk, group = risk) + geom_point() + facet_grid(~ age)
a1 + aes(color = age, group = age) + geom_point() + facet_grid(~ risk)

# 20% VE
a2 <- ggplot(df_20, aes(x = dalys.averted.per100k, y = cost.diff.per100k)) + l +
  labs(title = "Cost-effectiveness plane: Healthy People vs. Prevalent (20% VE)")
a2 + aes(color = risk, group = risk) + geom_point() + facet_grid(~ age)
a2 + aes(color = age, group = age) + geom_point() + facet_grid(~ risk)
```


## EXTRA: Combine HP 20% + PV 40%

```{r eval=FALSE, include=FALSE}
# bind HP table + PV table
df_all <- bind_rows(df_20, df_40)

# factor
df_all$scenario <- factor(df_all$scenario, labels = c("Prevalent Scenario (compared to no vaccination)", "Healthy People Scenario (compared to prevalent)"))
```

## EXTRA: HP 20% and PV 40%: ICERs
```{r eval=FALSE, include=FALSE}
ggplot(df_all, aes(x = age, y = icer.case.averted, group = risk, color = risk)) +
  geom_point() + geom_line(linetype = "dotted") + labs(x = "Age group", color = "Risk group") + 
  ylab("$ saved per case averted") + ggtitle("ICER per case averted") +
  facet_grid(~ scenario)

ggplot(df_all, aes(x = age, y = icer.death.averted, group = risk, color = risk)) +
  geom_point() + geom_line(linetype = "dotted") + labs(x = "Age group", color = "Risk group") + 
  ylab("$ saved per death averted") + ggtitle("ICER per death averted") +
  facet_grid(~ scenario)

ggplot(df_all, aes(x = age, y = icer.daly.averted, group = risk, color = risk)) +
  geom_point() + geom_line(linetype = "dotted") + labs(x = "Age group", color = "Risk group") + 
  ylab("$ saved per DALY averted") + ggtitle("ICER per DALY averted") +
  facet_grid(~ scenario)
```

## EXTRA: HP 20% and PV 40%: Cases
```{r eval=FALSE, include=FALSE}
g <- ggplot(df_all, aes(x = age, group = risk, color = risk)) +
  geom_point() + geom_line(linetype = "dotted") + labs(x = "Age group", color = "Risk group") +
  facet_grid(~ scenario)

g + aes(y = cases) + labs(y = "Cases", title = "Cases")
g + aes(y = cases.per100k) + labs(y = "Cases per 100k", title = "Cases per 100k")
g + aes(y = cases.averted) + labs(y = "Cases averted", title = "Cases averted")
g + aes(y = cases.averted.per100k) + labs(y = "Cases averted per 100k", title = "Cases averted per 100k")
```

## EXTRA: HP 20% and PV 40%: Deaths
```{r eval=FALSE, include=FALSE}
g + aes(y = deaths) + labs(y = "Deaths", title = "Deaths")
g + aes(y = deaths.per100k) + labs(y = "Deaths per 100k", title = "Deaths per 100k")
g + aes(y = deaths.averted) + labs(y = "Deaths averted", title = "Deaths averted")
g + aes(y = deaths.averted.per100k) + labs(y = "Deaths averted per 100k", title = "Deaths averted per 100k")
```

## EXTRA: HP 20% and PV 40%: DALYs
```{r eval=FALSE, include=FALSE}
g + aes(y = dalys) + labs(y = "DALYs", title = "DALYs")
g + aes(y = dalys.per100k) + labs(y = "DALYs per 100k", title = "DALYs per 100k")
g + aes(y = dalys.averted) + labs(y = "DALYs averted", title = "DALYs averted")
g + aes(y = dalys.averted.per100k) + labs(y = "DALYs averted per 100k", title = "DALYs averted per 100k")
```

